### ISSUE TITLE
Git build problem

### ISSUE THREAD

**Issue by kle0py** [camialtr/jd-tools#1]
Hello, I can't build the solution, Visual Code Studio has marked that it can't find MoveSpaceWrapper :/

**Comment by camialtr** [comment]
Hii, that happen because there's a dll missing. Unfortunately, this is a private ubisoft resource that only some people have access to. This tool isn't maded to work with vscode until tha past days, as you can see the commits, i've haved to adapt it to work on. In the end, this tool is maded for only for selected ppl to use and there's no public functions that can be used without some private resources for now. Actually, this repository is only public for possible job interviews in the future.
